/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterTSol from "./Counter.t.sol";
export type { counterTSol };
export type { Counter } from "./Counter";
export type { ShadowVault } from "./ShadowVault";
