/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface ShadowVaultInterface extends Interface {
    getFunction(nameOrSignature: "accrueYield" | "apyBps" | "computeScore" | "confidentialProtocolId" | "deposit" | "getEncryptedBalance" | "getEncryptedScore" | "getVaultStats" | "hasDeposited" | "hasProfile" | "lastYieldTime" | "owner" | "proveBalanceAbove" | "proveLoanEligibility" | "proveScoreAbove" | "renounceOwnership" | "setAPY" | "totalTransactions" | "totalUsers" | "transferOwnership" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "OwnershipTransferred" | "ProofGenerated" | "ScoreUpdated" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'accrueYield', values: [AddressLike[]]): string;
encodeFunctionData(functionFragment: 'apyBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'computeScore', values: [BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'confidentialProtocolId', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getEncryptedBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEncryptedScore', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVaultStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasDeposited', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasProfile', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastYieldTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proveBalanceAbove', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proveLoanEligibility', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proveScoreAbove', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAPY', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalTransactions', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalUsers', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'accrueYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'apyBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confidentialProtocolId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEncryptedBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEncryptedScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaultStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasProfile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastYieldTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proveBalanceAbove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proveLoanEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proveScoreAbove', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTransactions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [user: string, timestamp: bigint];
      export interface OutputObject {user: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofGeneratedEvent {
      export type InputTuple = [user: AddressLike, proofType: string, timestamp: BigNumberish];
      export type OutputTuple = [user: string, proofType: string, timestamp: bigint];
      export interface OutputObject {user: string, proofType: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScoreUpdatedEvent {
      export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [user: string, timestamp: bigint];
      export interface OutputObject {user: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [user: string, timestamp: bigint];
      export interface OutputObject {user: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ShadowVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ShadowVault;
    waitForDeployment(): Promise<this>;

    interface: ShadowVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    accrueYield: TypedContractMethod<
      [users: AddressLike[], ],
      [void],
      'nonpayable'
    >
    

    
    apyBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    computeScore: TypedContractMethod<
      [encryptedIncome: BytesLike, incomeProof: BytesLike, encryptedDebt: BytesLike, debtProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    confidentialProtocolId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getEncryptedBalance: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getEncryptedScore: TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >
    

    
    getVaultStats: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {users: bigint, transactions: bigint, currentApy: bigint, lastYield: bigint }],
      'view'
    >
    

    
    hasDeposited: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasProfile: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    lastYieldTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proveBalanceAbove: TypedContractMethod<
      [threshold: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    proveLoanEligibility: TypedContractMethod<
      [loanAmount: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    proveScoreAbove: TypedContractMethod<
      [threshold: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAPY: TypedContractMethod<
      [newApyBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalTransactions: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalUsers: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'accrueYield'): TypedContractMethod<
      [users: AddressLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'apyBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'computeScore'): TypedContractMethod<
      [encryptedIncome: BytesLike, incomeProof: BytesLike, encryptedDebt: BytesLike, debtProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confidentialProtocolId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEncryptedBalance'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getEncryptedScore'): TypedContractMethod<
      [user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getVaultStats'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint] & {users: bigint, transactions: bigint, currentApy: bigint, lastYield: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasDeposited'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasProfile'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastYieldTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proveBalanceAbove'): TypedContractMethod<
      [threshold: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proveLoanEligibility'): TypedContractMethod<
      [loanAmount: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proveScoreAbove'): TypedContractMethod<
      [threshold: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAPY'): TypedContractMethod<
      [newApyBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalTransactions'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalUsers'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [encryptedAmount: BytesLike, inputProof: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProofGenerated'): TypedContractEvent<ProofGeneratedEvent.InputTuple, ProofGeneratedEvent.OutputTuple, ProofGeneratedEvent.OutputObject>;
getEvent(key: 'ScoreUpdated'): TypedContractEvent<ScoreUpdatedEvent.InputTuple, ScoreUpdatedEvent.OutputTuple, ScoreUpdatedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProofGenerated(address,string,uint256)': TypedContractEvent<ProofGeneratedEvent.InputTuple, ProofGeneratedEvent.OutputTuple, ProofGeneratedEvent.OutputObject>;
      ProofGenerated: TypedContractEvent<ProofGeneratedEvent.InputTuple, ProofGeneratedEvent.OutputTuple, ProofGeneratedEvent.OutputObject>;
    

      'ScoreUpdated(address,uint256)': TypedContractEvent<ScoreUpdatedEvent.InputTuple, ScoreUpdatedEvent.OutputTuple, ScoreUpdatedEvent.OutputObject>;
      ScoreUpdated: TypedContractEvent<ScoreUpdatedEvent.InputTuple, ScoreUpdatedEvent.OutputTuple, ScoreUpdatedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }