/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface FHEInterface extends utils.Interface {
  functions: {};

  events: {
    "PublicDecryptionVerified(bytes32[],bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PublicDecryptionVerified"): EventFragment;
}

export interface PublicDecryptionVerifiedEventObject {
  handlesList: string[];
  abiEncodedCleartexts: string;
}
export type PublicDecryptionVerifiedEvent = TypedEvent<
  [string[], string],
  PublicDecryptionVerifiedEventObject
>;

export type PublicDecryptionVerifiedEventFilter =
  TypedEventFilter<PublicDecryptionVerifiedEvent>;

export interface FHE extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FHEInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "PublicDecryptionVerified(bytes32[],bytes)"(
      handlesList?: null,
      abiEncodedCleartexts?: null
    ): PublicDecryptionVerifiedEventFilter;
    PublicDecryptionVerified(
      handlesList?: null,
      abiEncodedCleartexts?: null
    ): PublicDecryptionVerifiedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
