/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  ZamaConfig,
  ZamaConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/ZamaConfig";

const _abi = [
  {
    inputs: [],
    name: "ZamaProtocolUnsupported",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122099fd09f004bdb0c430046a8fdbe11620a58cea4bb8dd42de951d3992f5c131bf64736f6c634300081c0033";

type ZamaConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ZamaConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ZamaConfig__factory extends ContractFactory {
  constructor(...args: ZamaConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ZamaConfig> {
    return super.deploy(overrides || {}) as Promise<ZamaConfig>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ZamaConfig {
    return super.attach(address) as ZamaConfig;
  }
  override connect(signer: Signer): ZamaConfig__factory {
    return super.connect(signer) as ZamaConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ZamaConfigInterface {
    return new utils.Interface(_abi) as ZamaConfigInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ZamaConfig {
    return new Contract(address, _abi, signerOrProvider) as ZamaConfig;
  }
}
