/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ZamaEthereumConfig,
  ZamaEthereumConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/ZamaEthereumConfig";

const _abi = [
  {
    inputs: [],
    name: "ZamaProtocolUnsupported",
    type: "error",
  },
  {
    inputs: [],
    name: "confidentialProtocolId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ZamaEthereumConfig__factory {
  static readonly abi = _abi;
  static createInterface(): ZamaEthereumConfigInterface {
    return new utils.Interface(_abi) as ZamaEthereumConfigInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ZamaEthereumConfig {
    return new Contract(address, _abi, signerOrProvider) as ZamaEthereumConfig;
  }
}
