/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  FHE,
  FHEInterface,
} from "../../../../../@fhevm/solidity/lib/FHE.sol/FHE";

const _abi = [
  {
    inputs: [],
    name: "DeserializingDecryptionProofFail",
    type: "error",
  },
  {
    inputs: [],
    name: "EmptyDecryptionProof",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidKMSSignatures",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalidSigner",
        type: "address",
      },
    ],
    name: "KMSInvalidSigner",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "numSignatures",
        type: "uint256",
      },
    ],
    name: "KMSSignatureThresholdNotReached",
    type: "error",
  },
  {
    inputs: [],
    name: "KMSZeroSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "handle",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "SenderNotAllowedToUseHandle",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32[]",
        name: "handlesList",
        type: "bytes32[]",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "abiEncodedCleartexts",
        type: "bytes",
      },
    ],
    name: "PublicDecryptionVerified",
    type: "event",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea264697066735822122037253ce079e7ed1db6e3ac6b838712afb60ffa9bbdd3296759ce8d396cdfaa9964736f6c634300081c0033";

type FHEConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FHEConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FHE__factory extends ContractFactory {
  constructor(...args: FHEConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<FHE> {
    return super.deploy(overrides || {}) as Promise<FHE>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): FHE {
    return super.attach(address) as FHE;
  }
  override connect(signer: Signer): FHE__factory {
    return super.connect(signer) as FHE__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FHEInterface {
    return new utils.Interface(_abi) as FHEInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): FHE {
    return new Contract(address, _abi, signerOrProvider) as FHE;
  }
}
