/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../common";
import type {
  FhevmECDSA,
  FhevmECDSAInterface,
} from "../../../../../@fhevm/solidity/lib/cryptography/FhevmECDSA";

const _abi = [
  {
    inputs: [],
    name: "ECDSAInvalidSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "ECDSAInvalidSignatureLength",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "ECDSAInvalidSignatureS",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212206fd313eea45605312dabfa516bbab76350b642901071964eaa1e2a80d78e2b2364736f6c634300081c0033";

type FhevmECDSAConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FhevmECDSAConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FhevmECDSA__factory extends ContractFactory {
  constructor(...args: FhevmECDSAConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<FhevmECDSA> {
    return super.deploy(overrides || {}) as Promise<FhevmECDSA>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): FhevmECDSA {
    return super.attach(address) as FhevmECDSA;
  }
  override connect(signer: Signer): FhevmECDSA__factory {
    return super.connect(signer) as FhevmECDSA__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FhevmECDSAInterface {
    return new utils.Interface(_abi) as FhevmECDSAInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FhevmECDSA {
    return new Contract(address, _abi, signerOrProvider) as FhevmECDSA;
  }
}
